# Generated by Django 5.0.6 on 2024-06-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="level_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
