# Generated by Django 5.0.6 on 2024-06-15 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0002_level_level_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="level",
            options={
                "ordering": ["level_number"],
                "verbose_name": "Уровень",
                "verbose_name_plural": "Уровни",
            },
        ),
        migrations.AlterField(
            model_name="subject",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="studies.level",
                verbose_name="Уровень",
            ),
        ),
    ]
