# Generated by Django 5.0.6 on 2024-06-15 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0003_alter_level_options_alter_subject_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="studies.subject",
                verbose_name="Тема",
            ),
        ),
    ]
