# Generated by Django 5.0.6 on 2024-06-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_tag_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="posts.tag"
            ),
        ),
    ]
